// Package eventtypes — Catalog pha/bước E2E (G1–G6) cho frontend tra cứu; khớp docs/flows/bang-pha-buoc-event-e2e.md §5.2–5.3.
// G1 = pha ghi thô (CIO ingress → L1 → enqueue). G1-S04 = một dòng catalog «báo thay đổi L1» vào decision_events_queue.
// G2 = merge L2 + consumer: G2-S01 = consumer lease một job decision_events_queue — trên trục merge (L1→L2) điển hình là một job báo đổi L1 (eventSource l1_datachanged, sau G1-S04); cùng bước lease vẫn dùng cho mọi job queue khác. G2-S05 (crmqueue sau merge) đưa job vào queue — l2_datachanged + after_l2_merge + <prefix>.changed (fallback recompute_requested); bản ghi cũ crm_merge_queue. Gom debounce; gấp = bỏ/rút ngắn gom.
// G3 = intel miền — G3-S01…S05 như trên; G3-S06 catalog: worker miền phát <domain>_intel_recomputed lên decision_events_queue. Envelope queue của job đó (AID consumer) — ResolveE2EForQueueEnvelope → G4-S01 (pha quyết định).
// Khung G1–G6 là tham chiếu toàn trình; event thực tế có thể vào/thoát luồng ở bất kỳ bước — xem docs/flows/bang-pha-buoc-event-e2e.md (mục «Khung tham chiếu vs thực tế»).
package eventtypes

// E2ECatalogSchemaVersion — tăng khi đổi hình dạng JSON hoặc cắt bớt cột (client cache).
const E2ECatalogSchemaVersion = 35 // v35: bỏ bước catalog G4-S04 — gộp execute/propose (E01–E03) vào G4-S03; resolver/livePhase e2eStepId G4-S03-E*; v34: batch→G2-S02; v33: G4-S02 context một dòng; v31: *_intel_recomputed → G4-S01; v30: G3-S02 + G3-S06; v29–v10: …

// E2EStageCatalogEntry — một giai đoạn lớn (bảng §5.2).
type E2EStageCatalogEntry struct {
	ID            string `json:"id"`                    // G1…G6
	SwimlaneCode  string `json:"swimlaneCode"`          // Mã lưu đồ §1.1, có thể ghép "ING,DOM"
	TitleVi       string `json:"titleVi"`               // Tên giai đoạn
	SummaryVi     string `json:"summaryVi"`             // Mô tả kỹ thuật / luồng máy
	UserSummaryVi string `json:"userSummaryVi"`         // Mô tả thân thiện cho người dùng cuối (timeline / onboarding)
	IngressHint   string `json:"ingressHint,omitempty"` // Pha chính (trục vụ)
}

// E2EStepCatalogEntry — một dòng bảng chi tiết §5.3 (bước + sự kiện + queue fields).
type E2EStepCatalogEntry struct {
	StageID                string `json:"stageId"`                       // G1…
	StepID                 string `json:"stepId"`                        // Gx-Syy
	EventDetailID          string `json:"eventDetailId,omitempty"`       // Gx-Syy-Ezz khi có
	DescriptionTechnicalVi string `json:"descriptionTechnicalVi"`        // Mô tả kỹ thuật (tra code, audit)
	DescriptionUserVi      string `json:"descriptionUserVi"`             // Mô tả thân thiện end-user (UI tooltip)
	EventType              string `json:"eventType,omitempty"`           // — → rỗng
	EventSource            string `json:"eventSource,omitempty"`         //
	PipelineStage          string `json:"pipelineStage,omitempty"`       //
	ResponsibilityGroup    string `json:"responsibilityGroup,omitempty"` // Nhóm trách nhiệm / swimlane tổng quát
}

// E2EStageCatalog — bảng giai đoạn lớn §5.2 (bản chữ trong code; đổi doc thì sửa đồng bộ).
func E2EStageCatalog() []E2EStageCatalogEntry {
	return []E2EStageCatalogEntry{
		{ID: E2EStageG1, SwimlaneCode: "ING,DOM", TitleVi: "Pha ghi thô: CIO ingress → L1 → datachanged → enqueue", SummaryVi: "CIO/sync → L1 → EmitDataChanged → decision_events_queue (eventSource l1_datachanged)", UserSummaryVi: "Dữ liệu từ cửa hàng và kênh chat được thu về, lưu nhất quán; hệ thống ghi nhận thay đổi và chuẩn bị đưa vào hàng đợi xử lý của trợ lý.", IngressHint: "Pha ghi thô"},
		{ID: E2EStageG2, SwimlaneCode: "AID,DOM", TitleVi: "Pha merge: consumer queue + hợp nhất canonical (L2)", SummaryVi: "Trục vụ sau đổi L1: ưu tiên merge canonical (L2) với gom (debounce/cửa sổ); gấp chỉ bỏ hoặc rút ngắn gom, vẫn đủ luồng consumer. (1) decision_events_queue — G2-S01 lease một job (trên trục merge điển hình một job l1_datachanged từ G1-S04; cùng lease cho mọi job queue khác) → G2-S02 processEvent: side-effect có thể xếp job merge cho miền (minh hoạ CRM: crm_pending_merge — AID không tự merge L2 trên consumer), rồi routing / dispatchConsumerEvent. (2) Worker miền G2-S03–S04 merge L1→L2; G2-S05-E01 enqueue lại decision_events_queue — cùng ý «báo thay đổi dữ liệu để AID xử lý tiếp» như G1-S04 nhưng sau L2 (wire: l2_datachanged, <prefix>.changed từ collection nguồn, after_l2_merge; fallback crm.intelligence.recompute_requested nếu không map collection; bản ghi cũ có thể crm_merge_queue + recompute_requested).", UserSummaryVi: "Thay đổi nguồn được xếp hàng; trợ lý chuyển yêu cầu gộp sang worker miền; khi hồ sơ chung (L2) cập nhật, miền báo lại lên hàng đợi AID giống cách báo đổi L1 ở bước trước — để các bước sau chạy tiếp. Có thể gom hoặc ưu tiên trước khi cấp bách.", IngressHint: "Pha merge"},
		{ID: E2EStageG3, SwimlaneCode: "INT", TitleVi: "Pha intel miền và bàn giao về AID", SummaryVi: "Ba bước trục vụ: (1) G3-S01 — consumer AID nhận job trên decision_events_queue; điển hình báo đổi L2 (l2_datachanged, after_l2_merge, <prefix>.changed sau G2-S05-E01); một dòng catalog gom mọi yêu cầu intel/recompute/analysis (prefix miền). (2) G3-S02 — AID tính toán/xếp việc: routing (nhánh l2 post-merge, consumerreg…), gom (debounce/cửa sổ, trailing…), gấp (urgent / policy → enqueue sớm), rồi enqueue job *_intel_compute vào hàng đợi từng miền liên quan (crm_intel_compute, ads_intel_compute, order_intel_compute, cix_intel_compute, …). (3) Worker miền G3-S03…S05 (lease → pipeline → read model) rồi G3-S06 miền phát *_intel_recomputed lên decision_events_queue — AID nhận bản ghi đó ở pha G4 (catalog G4-S01, resolver envelope).", UserSummaryVi: "(1) Trợ lý nhận tín hiệu trên hàng đợi — thường sau khi L2 cập nhật (l2_datachanged). (2) Trợ lý quyết định và xếp việc tính lại intelligence cho từng miền (gom/gấp rồi tạo job trên hàng đợi worker miền). (3) Miền chạy xong thì bắn kết quả về hàng đợi trợ lý; trợ lý xử lý tiếp ở bước case (G4).", IngressHint: "Pha intel"},
		{ID: E2EStageG4, SwimlaneCode: "AID", TitleVi: "Pha ra quyết định: case, ngữ cảnh, điều phối", SummaryVi: "decision_cases_runtime — bốn bước trục vụ (handoff intel; luồng khác có thể rút gọn): (1) G4-S01 — worker AID xử lý job <domain>_intel_recomputed trên decision_events_queue, ResolveOrCreate / cập nhật case. (2) AID rà soát ngữ cảnh; thiếu → job / *.context_requested tới Domain (catalog G4-S02). (3) Domain báo *.context_ready — cùng G4-S02; lặp (2)↔(3) khi cần. (4) G4-S03 — HasAllRequiredContexts + policy + engine (parse/LLM/decision/policy; live phase map cùng bước) + phát aidecision.execute_requested / executor.propose_requested (chi tiết catalog G4-S03-E01…E03). Gom tin message.batch_ready không còn bước catalog G4 — envelope neo G2-S02 khi consumer xử lý job.", UserSummaryVi: "(1) Nhận báo intel đã tính lại và cập nhật vụ. (2) Thiếu ngữ cảnh thì nhờ từng miền bổ sung. (3) Miền báo đã gửi ngữ cảnh. (4) Suy luận, chọn hành động và tạo lệnh thực thi hoặc đề xuất cho Executor.", IngressHint: "Pha ra quyết định"},
		{ID: E2EStageG5, SwimlaneCode: "EXC", TitleVi: "Pha thực thi (Executor)", SummaryVi: "Duyệt, dispatch adapter, chạy action", UserSummaryVi: "Lệnh được duyệt (tự động hoặc có người) và gửi tới hệ thống thực thi để hoàn tất việc cần làm.", IngressHint: "Pha thực thi"},
		{ID: E2EStageG6, SwimlaneCode: "OUT,LRN,FBK", TitleVi: "Pha học: outcome, learning_cases, feedback", SummaryVi: "Outcome → learning_cases → evaluation → gợi ý rule/policy", UserSummaryVi: "Kết quả thực tế được ghi nhận; hệ thống học từ phản hồi để gợi ý cải tiến quy tắc và trải nghiệm sau này.", IngressHint: "Pha học"},
	}
}

// E2EStepCatalog — bảng chi tiết §5.3 (một bảng thống nhất).
func E2EStepCatalog() []E2EStepCatalogEntry {
	return []E2EStepCatalogEntry{
		{StageID: E2EStageG1, StepID: "G1-S01", DescriptionTechnicalVi: "CIO / kênh ingress nhận dữ liệu từ nguồn bên ngoài (webhook, job sync kênh, callback…); xác thực & ghi nhận — chưa ghi L1", DescriptionUserVi: "Cửa hàng nhận tin từ khách qua các kênh (webhook, đồng bộ…); mới kiểm tra và ghi nhận, chưa lưu vào kho dữ liệu nội bộ.", ResponsibilityGroup: "CIO"},
		{StageID: E2EStageG1, StepID: "G1-S02", DescriptionTechnicalVi: "CIO xử lý payload: chuẩn hoá, map schema; ghi mirror / L1-persist (DoSyncUpsert) hoặc CRUD domain", DescriptionUserVi: "Dữ liệu nghiệp vụ được chuẩn hoá và lưu bản ghi nguồn (L1) cho các bước sau.", ResponsibilityGroup: "CIO"},
		{StageID: E2EStageG1, StepID: "G1-S03", DescriptionTechnicalVi: "Sau khi ghi L1 thành công: phát EmitDataChanged (bus nội bộ). Handler AID (hooks/datachanged) lọc collection: source_sync registry + ShouldEmitDatachangedToDecisionQueue — chỉ hợp lệ mới enqueue G1-S04", DescriptionUserVi: "Sau khi lưu xong, hệ thống báo nội bộ có thay đổi; chỉ những loại dữ liệu đã cấu hình mới được chuyển tiếp tới hàng đợi trợ lý.", ResponsibilityGroup: "CIO"},
		{StageID: E2EStageG1, StepID: "G1-S04", DescriptionTechnicalVi: "Enqueue decision_events_queue — bước catalog «báo thay đổi L1» (mirror/L1-persist) để AID xử lý tiếp; tương tự ý enqueue sau cập nhật canonical ở G2-S05-E01 nhưng tầng L1. Payload: sourceCollection, dataChangeOperation (insert/update/upsert). eventType = <prefix>.changed — prefix map từ tên collection (source_sync_registry). consumerreg.Lookup tương thích *.inserted/*.updated. eventSource = l1_datachanged.", DescriptionUserVi: "Mỗi thay đổi nguồn đã đăng ký được đưa vào hàng đợi trợ lý; loại bản ghi biết qua collection.", EventType: "<prefix>.changed — prefix từ collection; eventSource l1_datachanged", EventSource: "l1_datachanged", PipelineStage: "after_l1_change", ResponsibilityGroup: "CIO"},
		{StageID: E2EStageG2, StepID: "G2-S01", DescriptionTechnicalVi: "AIDecisionConsumerWorker lease một bản ghi decision_events_queue — bắt đầu processEvent. Trên trục pha merge (L1→L2), điển hình là một job báo đổi L1: eventSource l1_datachanged, pipelineStage after_l1_change (sau G1-S04). Cùng bước lease áp dụng cho mọi job khác trên queue (l2_datachanged, *_intel_recomputed, …) — mốc timeline consumer vẫn neo G2-S01 mỗi lần lease.", DescriptionUserVi: "Máy lấy một việc đã xếp hàng; trên luồng merge thường là một sự kiện báo đổi L1 (l1_datachanged).", ResponsibilityGroup: "AID"},
		{StageID: E2EStageG2, StepID: "G2-S02", DescriptionTechnicalVi: "Sau G2-S01, toàn bộ processEvent trên consumer. Với nguồn L1-datachanged: gom — cửa sổ debounce (ResolveDatachangedDeferWindowsViaRule), trì hoãn/xếp lại side-effect và debounce intel (trailing…); gấp — chỉ bỏ qua hoặc rút ngắn các bước gom (không chờ đủ cửa sổ, ưu tiên xử lý ngay và trước) qua ClassifyDatachangedBusinessUrgency, immediateSideEffects / urgentSideEffects / Realtime khi policy bật — không cắt luồng: vẫn applyDatachangedSideEffects đầy đủ (hydrate, Mongo, datachangedsidefx.Run — minh hoạ CRM: có thể ghi crm_pending_merge là yêu cầu merge cho worker miền, không merge L2 tại goroutine consumer; report…), rồi ShouldSkipDispatchForRoutingRule → noop hoặc dispatchConsumerEvent — consumerreg.Lookup → handler (orchestrate, intel, Ads…) hoặc no_handler. Mốc queue datachanged_done / handler_done / handler_error / routing_skipped / no_handler đều neo catalog G2-S02. Sau khi worker miền merge xong, minh hoạ: miền emit lại decision_events_queue (l2_datachanged + <prefix>.changed + after_l2_merge; consumer route thẳng debounce crm intel, không Lookup .changed như L1) — bước catalog G2-S03–G2-S05-E01.", DescriptionUserVi: "Có thể gom nhiều cập nhật theo cửa sổ (debounce) để đỡ tải; khi gấp, bỏ phần gom và ưu tiên trước nhưng vẫn qua đủ đồng bộ — có thể gửi yêu cầu gộp sang worker miền; khi miền xong, việc quay lại hàng đợi trợ lý để chạy tiếp.", ResponsibilityGroup: "AID"},
		{StageID: E2EStageG2, StepID: "G2-S03", DescriptionTechnicalVi: "Worker miền lấy job gộp L1→L2 — tách khỏi consumer G2-S01–S02 (queue/worker theo từng miền dữ liệu). Minh hoạ CRM: đọc crm_pending_merge (CrmPendingMergeWorker), không chạy trong consumer AID.", DescriptionUserVi: "Worker miền nhận việc gộp đã xếp từ bước trước (vd. hàng đợi merge CRM) và thực hiện gộp dữ liệu.", ResponsibilityGroup: "DomainData"},
		{StageID: E2EStageG2, StepID: "G2-S04", DescriptionTechnicalVi: "Áp merge: ghi canonical (uid, sourceIds, links).", DescriptionUserVi: "Cập nhật hồ sơ chung để mọi kênh trỏ cùng một thực thể.", ResponsibilityGroup: "DomainData"},
		{StageID: E2EStageG2, StepID: "G2-S05", EventDetailID: "G2-S05-E01", DescriptionTechnicalVi: "Sau merge L2: enqueue decision_events_queue — bước catalog «báo thay đổi / cập nhật sau L2» (canonical đã gộp) để AID xử lý tiếp, cùng vai trò nghiệp vụ với G1-S04 (báo đổi L1) nhưng tầng L2. Minh hoạ CRM: notify_after_crm_merge → crmqueue.EmitAfterL2MergeForCrmIntel — eventSource l2_datachanged, pipelineStage after_l2_merge, eventType <prefix>.changed map từ collection nguồn (eventtypes/source_collection_wire.go, đồng bộ hooks/source_sync_registry); nếu không map được collection thì fallback crm.intelligence.recompute_requested. Consumer AID: nhánh IsPostL2MergeCrmIntelEnvelope → processCrmIntelligenceRecomputeRequested — pha catalog G3-S01 (nhận job) / G3-S02 (xếp crm_intel_compute: debounce hoặc enqueue), không dispatch Lookup .changed như L1. Bản ghi queue cũ có thể còn crm_merge_queue + recompute_requested (resolver vẫn neo G2-S05-E01).", DescriptionUserVi: "Miền gộp xong hồ sơ chung (L2) rồi báo thay đổi lên hàng đợi AID như bước báo đổi L1 — để trợ lý xử lý tiếp.", EventType: "<prefix>.changed — prefix từ collection; eventSource l2_datachanged", EventSource: "l2_datachanged", PipelineStage: "after_l2_merge", ResponsibilityGroup: "DomainData"},
		{StageID: E2EStageG3, StepID: "G3-S01", DescriptionTechnicalVi: "Trên trục pha intel (G3), consumer AID đã lease job decision_events_queue và đang xử lý envelope intel: điển hình báo đổi L2 — eventSource l2_datachanged, pipelineStage after_l2_merge, eventType <prefix>.changed (chuỗi sau G2-S05-E01; minh hoạ EmitAfterL2MergeForCrmIntel). Chú ý resolver envelope: bản ghi <prefix>.changed + l2 có thể neo G2-S05-E01 (bước emit sau merge L2), không phải G3-S01. G3-S01 là một dòng catalog gom mọi **loại job đầu vào** yêu cầu intel/recompute/analysis theo prefix miền (crm.*, ads.*, order.*, cix.*) — kể cả không từ l2_datachanged. Bước **tính toán và enqueue** job *_intel_compute nằm ở **G3-S02**. Sau khi miền phát handoff (catalog **G3-S06**), bản ghi `*_intel_recomputed` trên queue được **ResolveE2EForQueueEnvelope** neo **G4-S01**. Tra ResolveE2EForQueueEnvelope + consumerreg.", DescriptionUserVi: "Trợ lý đang xử lý một việc trên hàng đợi liên quan làm mới phân tích — thường là báo đổi L2 sau khi hồ sơ chung cập nhật; cùng một bước catalog cho các tên yêu cầu intel khác trên wire.", EventType: "<domain>.* — crm | ads | order | cix (vd. crm.intelligence.*_requested); điển hình sau L2: <prefix>.changed + l2_datachanged", EventSource: "điển hình l2_datachanged; tuỳ miền và emit (crm, meta_*, aidecision, …)", PipelineStage: "điển hình after_l2_merge; tuỳ emit (after_l1_change, external_ingest, …)", ResponsibilityGroup: "AID"},
		{StageID: E2EStageG3, StepID: "G3-S02", DescriptionTechnicalVi: "AID — sau khi đã nhận job (G3-S01): routing và **tính toán xếp việc** để tạo/enqueue các job tính lại intelligence trên hàng đợi worker từng miền (*_intel_compute). Minh hoạ CRM sau L2: IsPostL2MergeCrmIntelEnvelope → processCrmIntelligenceRecomputeRequested → gom ScheduleCrmIntelligenceRecomputeDebounce (cửa sổ/trailing) hoặc gấp EnqueueCrmIntelComputeFromDecisionEvent (PayloadMarksIntelUrgent, debounce tắt, cửa sổ 0…). Tương tự các nhánh consumer khác (consumerreg.Lookup, emit service…) map nhu cầu sang đúng miền (crm / ads / order / cix / …). Không chạy pipeline intel nặng tại bước này — worker miền đảm nhiệm ở G3-S03…S05.", DescriptionUserVi: "Trợ lý quyết định miền nào cần tính lại phân tích, có thể gom hoặc ưu tiên xếp ngay, rồi tạo việc trên hàng đợi chuyên trách từng miền.", ResponsibilityGroup: "AID"},
		{StageID: E2EStageG3, StepID: "G3-S03", DescriptionTechnicalVi: "Worker miền lease/lấy job từ hàng đợi *_intel_compute (sau G3-S02).", DescriptionUserVi: "Máy chuyên trách từng miền bắt đầu chạy phân tích đã được trợ lý giao.", ResponsibilityGroup: "DomainIntel"},
		{StageID: E2EStageG3, StepID: "G3-S04", DescriptionTechnicalVi: "Chạy pipeline phân tích (rule/LLM/snapshot)", DescriptionUserVi: "Áp quy tắc và mô hình để tóm tắt, đánh giá hoặc gắn nhãn theo cấu hình.", ResponsibilityGroup: "DomainIntel"},
		{StageID: E2EStageG3, StepID: "G3-S05", DescriptionTechnicalVi: "Ghi bản ghi chạy intel + cập nhật read model", DescriptionUserVi: "Kết quả phân tích được lưu để màn hình và trợ lý đọc nhanh, không phải tính lại mỗi lần.", ResponsibilityGroup: "DomainIntel"},
		{StageID: E2EStageG3, StepID: "G3-S06", DescriptionTechnicalVi: "Sau khi worker miền tính toán xong intelligence: **phía miền** phát sự kiện dạng <domain>_intel_recomputed lên decision_events_queue (vd. cix_intel_recomputed, crm_intel_recomputed, order_intel_recomputed, campaign_intel_recomputed); eventSource/pipelineStage từng miền (cix_intel, crm_intel, order_intel, meta_ads_intel, domain_intel). Bước catalog mô tả **emit** từ DomainIntel; khi AID consumer đọc bản ghi queue đó, **ResolveE2EForQueueEnvelope** neo **G4-S01** (nhận event — pha case). LabelVi theo eventType ở resolver.", DescriptionUserVi: "Miền chạy xong phân tích và bắn handoff intel lên hàng đợi; trợ lý sẽ nhận ở bước case (G4-S01).", EventType: "<domain>_intel_recomputed — vd. cix, crm, order, campaign (Ads)", EventSource: "cix_intel, crm_intel, order_intel, meta_ads_intel", PipelineStage: "domain_intel", ResponsibilityGroup: "DomainIntel"},
		{StageID: E2EStageG4, StepID: "G4-S01", DescriptionTechnicalVi: "ResolveOrCreate và cập nhật decision_cases_runtime. **Điển hình nhận job** trên decision_events_queue với eventType **<domain>_intel_recomputed** (sau khi miền phát ở catalog G3-S06) — AID vào pha quyết định, cập nhật case / điều phối tiếp (ngữ cảnh, orchestrate…). Tra ResolveE2EForQueueEnvelope — envelope `*_intel_recomputed` neo G4-S01, LabelVi theo từng eventType.", DescriptionUserVi: "Trợ lý mở hoặc cập nhật vụ việc — thường khi nhận bàn giao phân tích từ miền (intel_recomputed) hoặc các luồng case khác.", ResponsibilityGroup: "AID"},
		{StageID: E2EStageG4, StepID: "G4-S02", DescriptionTechnicalVi: "Điều phối ngữ cảnh bổ sung giữa AID và các miền — một dòng catalog gom *.context_requested (AID yêu cầu snapshot / dữ liệu nền; có thể xếp job tới worker Domain) và *.context_ready (Domain báo đã gửi ngữ cảnh). Chi tiết theo eventType; minh hoạ CRM: customer.context_requested / customer.context_ready (aidecision, crm); Ads: ads.context_* (aidecision, meta_ads_intel). Resolver queue: ResolveE2EForQueueEnvelope neo G4-S02, LabelVi theo từng eventType.", DescriptionUserVi: "Trợ lý nhờ miền bổ sung hoặc nhận báo ngữ cảnh đã tới — phân biệt requested vs ready qua eventType.", EventType: "<domain>.context_requested | <domain>.context_ready — vd. customer.*, ads.*", EventSource: "aidecision; crm; meta_ads_intel (tuỳ eventType)", PipelineStage: "aid_coordination", ResponsibilityGroup: "AID"},
		{StageID: E2EStageG4, StepID: "G4-S03", DescriptionTechnicalVi: "Sau khi đủ ngữ cảnh: kiểm HasAllRequiredContexts, áp policy, engine case (parse / LLM / decision / policy / ads_evaluate trong live phase) — tính toán logic để chọn hướng đề xuất hành động; hoàn tất / lỗi pipeline live map cùng bước (không eventDetailId). Phát lệnh sang Executor: chi tiết **G4-S03-E01…E03** (wire queue). Các phase live (trừ queued/propose chi tiết) map ResolveE2EForLivePhase neo G4-S03.", DescriptionUserVi: "Trợ lý xác nhận đủ thông tin, áp quy tắc, suy luận và chuẩn bị hoặc gửi hành động phù hợp.", ResponsibilityGroup: "AID"},
		{StageID: E2EStageG4, StepID: "G4-S03", EventDetailID: "G4-S03-E01", DescriptionTechnicalVi: "Phát lệnh thực thi trực tiếp (execute)", DescriptionUserVi: "Trợ lý chuẩn bị gửi hành động đi thực hiện (gửi tin, cập nhật hệ thống…).", EventType: "aidecision.execute_requested", EventSource: "aidecision", PipelineStage: "aid_coordination", ResponsibilityGroup: "AID"},
		{StageID: E2EStageG4, StepID: "G4-S03", EventDetailID: "G4-S03-E02", DescriptionTechnicalVi: "Tạo đề xuất hành động tại Executor (propose)", DescriptionUserVi: "Trợ lý tạo đề xuất để bạn hoặc hệ thống duyệt trước khi chạy.", EventType: "executor.propose_requested", EventSource: "aidecision", PipelineStage: "aid_coordination", ResponsibilityGroup: "AID"},
		{StageID: E2EStageG4, StepID: "G4-S03", EventDetailID: "G4-S03-E03", DescriptionTechnicalVi: "Event cũ tương thích cho Ads", DescriptionUserVi: "Luồng đề xuất quảng cáo kiểu cũ (tương thích hệ thống trước).", EventType: "ads.propose_requested (legacy)", EventSource: "aidecision", PipelineStage: "aid_coordination", ResponsibilityGroup: "AID"},
		{StageID: E2EStageG5, StepID: "G5-S01", DescriptionTechnicalVi: "Executor nhận proposal/action từ AI Decision", DescriptionUserVi: "Khối thực thi nhận lệnh hoặc đề xuất từ trợ lý.", ResponsibilityGroup: "Executor"},
		{StageID: E2EStageG5, StepID: "G5-S02", DescriptionTechnicalVi: "Duyệt theo policy (manual/auto/...)", DescriptionUserVi: "Hành động được duyệt tự động hoặc chờ người xác nhận tùy cài đặt.", ResponsibilityGroup: "Executor"},
		{StageID: E2EStageG5, StepID: "G5-S03", DescriptionTechnicalVi: "Dispatch adapter để thực thi", DescriptionUserVi: "Lệnh được gửi đúng kênh kỹ thuật (API, tin nhắn…) để hoàn tất.", ResponsibilityGroup: "Executor"},
		{StageID: E2EStageG6, StepID: "G6-S01", DescriptionTechnicalVi: "Ghi kết quả kỹ thuật (delivery/API response)", DescriptionUserVi: "Hệ thống ghi nhận đã gửi thành công hay lỗi kỹ thuật.", ResponsibilityGroup: "Outcome"},
		{StageID: E2EStageG6, StepID: "G6-S02", DescriptionTechnicalVi: "Thu kết quả nghiệp vụ theo time window", DescriptionUserVi: "Theo dõi kết quả thực tế sau một khoảng thời gian (theo cấu hình vụ việc).", ResponsibilityGroup: "Outcome"},
		{StageID: E2EStageG6, StepID: "G6-S03", DescriptionTechnicalVi: "Action chuyển trạng thái kết thúc (executed/rejected/failed)", DescriptionUserVi: "Việc được đánh dấu hoàn thành, từ chối hoặc thất bại rõ ràng.", ResponsibilityGroup: "Learning"},
		{StageID: E2EStageG6, StepID: "G6-S04", DescriptionTechnicalVi: "OnActionClosed → CreateLearningCaseFromAction → insert learning_cases", DescriptionUserVi: "Từ kết thúc việc, hệ thống tạo bản ghi học để đánh giá sau.", ResponsibilityGroup: "Learning"},
		{StageID: E2EStageG6, StepID: "G6-S05", DescriptionTechnicalVi: "Chạy RunEvaluationBatch / job đánh giá", DescriptionUserVi: "Chạy đợt đánh giá chất lượng gợi ý và kết quả.", ResponsibilityGroup: "Learning"},
		{StageID: E2EStageG6, StepID: "G6-S06", DescriptionTechnicalVi: "Ghi field evaluation (ví dụ outcome_class, attribution)", DescriptionUserVi: "Gắn nhãn kết quả (tốt/xấu, nguyên nhân) phục vụ báo cáo.", ResponsibilityGroup: "Learning"},
		{StageID: E2EStageG6, StepID: "G6-S07", DescriptionTechnicalVi: "Sinh param_suggestions, rule_candidate, insight", DescriptionUserVi: "Sinh gợi ý chỉnh tham số hoặc quy tắc dựa trên dữ liệu thực tế.", ResponsibilityGroup: "Feedback"},
		{StageID: E2EStageG6, StepID: "G6-S08", DescriptionTechnicalVi: "Đẩy ngược cải tiến lên Rule/Policy/AID (có thể có bước duyệt người)", DescriptionUserVi: "Gợi ý cải tiến được đưa lên bảng điều khiển quy tắc (có thể cần người duyệt).", ResponsibilityGroup: "Feedback"},
	}
}

// E2EQueueMilestoneCatalogEntry — mốc consumer (timeline) khớp ResolveE2EForQueueConsumerMilestone.
type E2EQueueMilestoneCatalogEntry struct {
	Key         string `json:"key"`     // processing_start | …
	StageID     string `json:"stageId"` // G2 (pha merge — consumer)
	StepID      string `json:"stepId"`
	LabelVi     string `json:"labelVi"`     // Mô tả kỹ thuật / máy
	UserLabelVi string `json:"userLabelVi"` // Mô tả thân thiện end-user
}

// E2EQueueMilestoneCatalog — các milestone nội bộ consumer (eventtypes.E2EQueueMilestone*).
func E2EQueueMilestoneCatalog() []E2EQueueMilestoneCatalogEntry {
	return []E2EQueueMilestoneCatalogEntry{
		{Key: E2EQueueMilestoneProcessingStart, StageID: E2EStageG2, StepID: "G2-S01", LabelVi: "Consumer lease job — điển hình l1_datachanged (trục merge); mọi job queue khác cũng qua bước này", UserLabelVi: "Hệ thống lấy một việc trên hàng đợi; thường là báo đổi dữ liệu nguồn (L1) để gộp hồ sơ."},
		{Key: E2EQueueMilestoneDatachangedDone, StageID: E2EStageG2, StepID: "G2-S02", LabelVi: "Hoàn tất tác vụ sau datachanged (consumer)", UserLabelVi: "Đã xong các bước đồng bộ sau khi dữ liệu thay đổi."},
		{Key: E2EQueueMilestoneHandlerDone, StageID: E2EStageG2, StepID: "G2-S02", LabelVi: "Đóng job consumer — handler hoàn tất", UserLabelVi: "Đã xử lý xong việc này trên hàng đợi."},
		{Key: E2EQueueMilestoneHandlerError, StageID: E2EStageG2, StepID: "G2-S02", LabelVi: "Lỗi xử lý trên consumer", UserLabelVi: "Có lỗi khi xử lý; có thể thử lại hoặc xem chi tiết lỗi."},
		{Key: E2EQueueMilestoneRoutingSkipped, StageID: E2EStageG2, StepID: "G2-S02", LabelVi: "Routing bỏ qua handler (noop)", UserLabelVi: "Theo cài đặt, bước tự động này được bỏ qua — không ảnh hưởng dữ liệu đã lưu."},
		{Key: E2EQueueMilestoneNoHandler, StageID: E2EStageG2, StepID: "G2-S02", LabelVi: "Chưa có handler đăng ký cho eventType", UserLabelVi: "Loại cập nhật này chưa được cấu hình xử lý tự động thêm."},
	}
}
