# GolangCI-Lint Configuration
# Version: 1.24.0+

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - api-tests
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    check-shadowing: true
    enable-all: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  maligned:
    suggest-new: true
  depguard:
    list-type: blacklist
    include-go-root: false
  lll:
    line-length: 140
  goimports:
    local-prefixes: meta_commerce
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gocritic
    - gocyclo
    - dupl
    - goconst
    - lll
    - nolintlint
  disable:
    - typecheck
    - deadcode
    - varcheck
    - structcheck
    - maligned
    - interfacer
    - scopelint
    - gochecknoinits
    - gochecknoglobals

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocyclo
        - dupl
        - goconst
    - path: api-tests
      linters:
        - errcheck
        - gocyclo
        - dupl
        - goconst
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
