// Package approval — Unit test cho Phase 2/3 Idempotency (Propose, ExecuteOne).
package approval

import (
	"context"
	"fmt"
	"testing"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// mockStorage implement Storage cho test — lưu trong map, hỗ trợ FindByIdempotencyKey.
type mockStorage struct {
	docs       map[string]*ActionPending // id hex -> doc
	byIdempKey map[string]*ActionPending // idempotencyKey -> doc đã xử lý
}

func newMockStorage() *mockStorage {
	return &mockStorage{
		docs:       make(map[string]*ActionPending),
		byIdempKey: make(map[string]*ActionPending),
	}
}

func (m *mockStorage) Insert(ctx context.Context, doc *ActionPending) error {
	if doc.ID.IsZero() {
		doc.ID = primitive.NewObjectID()
	}
	m.docs[doc.ID.Hex()] = doc
	return nil
}

func (m *mockStorage) Update(ctx context.Context, doc *ActionPending) error {
	m.docs[doc.ID.Hex()] = doc
	if doc.Status == StatusExecuted || doc.Status == StatusRejected || doc.Status == StatusFailed {
		if doc.Payload != nil {
			if idk, ok := doc.Payload["idempotencyKey"].(string); ok && idk != "" {
				m.byIdempKey[idk] = doc
			}
		}
	}
	return nil
}

func (m *mockStorage) FindById(ctx context.Context, id primitive.ObjectID, ownerOrgID primitive.ObjectID) (*ActionPending, error) {
	d, ok := m.docs[id.Hex()]
	if !ok {
		return nil, fmt.Errorf("không tìm thấy")
	}
	return d, nil
}

func (m *mockStorage) FindByIdempotencyKey(ctx context.Context, idempotencyKey string, ownerOrgID primitive.ObjectID) (*ActionPending, error) {
	if d, ok := m.byIdempKey[idempotencyKey]; ok {
		return d, nil
	}
	return nil, nil
}

func (m *mockStorage) FindPending(ctx context.Context, ownerOrgID primitive.ObjectID, domain string, limit int) ([]ActionPending, error) {
	return nil, nil
}
func (m *mockStorage) FindQueued(ctx context.Context, domain string, limit int) ([]ActionPending, error) {
	return nil, nil
}
func (m *mockStorage) Find(ctx context.Context, ownerOrgID primitive.ObjectID, filter FindFilter) ([]ActionPending, error) {
	return nil, nil
}
func (m *mockStorage) FindWithPagination(ctx context.Context, ownerOrgID primitive.ObjectID, filter FindWithPaginationFilter) ([]ActionPending, int64, error) {
	return nil, 0, nil
}
func (m *mockStorage) Count(ctx context.Context, ownerOrgID primitive.ObjectID, domain, status string, fromProposedAt, toProposedAt int64) (int64, error) {
	return 0, nil
}

// mockNotifier không gửi gì.
type mockNotifier struct{}

func (m *mockNotifier) Notify(ctx context.Context, eventType string, payload map[string]interface{}, ownerOrgID primitive.ObjectID, baseURL string) (int, error) {
	return 0, nil
}

func TestPropose_IdempotencyKeyAutoGenerated(t *testing.T) {
	ctx := context.Background()
	storage := newMockStorage()
	engine := NewEngine(storage, &mockNotifier{})
	engine.RegisterExecutor("ads", ExecutorFunc(func(ctx context.Context, doc *ActionPending) (map[string]interface{}, error) {
		return map[string]interface{}{"ok": true}, nil
	}))

	ownerID := primitive.NewObjectID()
	input := ProposeInput{
		ActionType: "KILL",
		Reason:     "test",
		Payload:    map[string]interface{}{"adAccountId": "act_123"},
	}

	doc, err := engine.Propose(ctx, "ads", input, ownerID, "http://localhost")
	if err != nil {
		t.Fatalf("Propose lỗi: %v", err)
	}
	if doc.Payload == nil {
		t.Fatal("payload không được nil")
	}
	if _, ok := doc.Payload["idempotencyKey"].(string); !ok {
		t.Error("Propose phải tự gán idempotencyKey khi thiếu")
	}
}

func TestPropose_IdempotencyReturnExisting_WhenAlreadyProcessed(t *testing.T) {
	ctx := context.Background()
	storage := newMockStorage()
	engine := NewEngine(storage, &mockNotifier{})
	engine.RegisterExecutor("ads", ExecutorFunc(func(ctx context.Context, doc *ActionPending) (map[string]interface{}, error) {
		return map[string]interface{}{"ok": true}, nil
	}))

	ownerID := primitive.NewObjectID()
	idempKey := "dc_abc:KILL:1700000000000"
	existingDoc := &ActionPending{
		ID:                  primitive.NewObjectID(),
		Domain:              "ads",
		ActionType:          "KILL",
		Status:              StatusExecuted,
		OwnerOrganizationID: ownerID,
		Payload:             map[string]interface{}{"idempotencyKey": idempKey, "adAccountId": "act_123"},
	}
	storage.docs[existingDoc.ID.Hex()] = existingDoc
	storage.byIdempKey[idempKey] = existingDoc

	input := ProposeInput{
		ActionType: "KILL",
		Reason:     "test duplicate",
		Payload:    map[string]interface{}{"adAccountId": "act_123", "idempotencyKey": idempKey},
	}

	doc, err := engine.Propose(ctx, "ads", input, ownerID, "http://localhost")
	if err != nil {
		t.Fatalf("Propose lỗi: %v", err)
	}
	if doc.ID != existingDoc.ID {
		t.Errorf("Propose phải trả doc đã xử lý (idempotency), got id %s", doc.ID.Hex())
	}
	if doc.Status != StatusExecuted {
		t.Errorf("doc trả về phải là executed, got %s", doc.Status)
	}
}

func TestExecuteOne_IdempotencySkip_WhenAlreadyProcessed(t *testing.T) {
	ctx := context.Background()
	storage := newMockStorage()
	engine := NewEngine(storage, &mockNotifier{})
	engine.RegisterExecutor("ads", ExecutorFunc(func(ctx context.Context, doc *ActionPending) (map[string]interface{}, error) {
		return map[string]interface{}{"ok": true}, nil
	}))

	ownerID := primitive.NewObjectID()
	idempKey := "ads:KILL:1700000000001"

	// Doc đã executed (khác ID) — idempotency đã xử lý
	executedDoc := &ActionPending{
		ID:                  primitive.NewObjectID(),
		Domain:              "ads",
		ActionType:          "KILL",
		Status:              StatusExecuted,
		OwnerOrganizationID: ownerID,
		Payload:             map[string]interface{}{"idempotencyKey": idempKey},
	}
	storage.byIdempKey[idempKey] = executedDoc

	// Doc queued đang chờ execute (cùng idempotencyKey)
	queuedDoc := &ActionPending{
		ID:                  primitive.NewObjectID(),
		Domain:              "ads",
		ActionType:          "KILL",
		Status:              StatusQueued,
		OwnerOrganizationID: ownerID,
		Payload:             map[string]interface{}{"idempotencyKey": idempKey},
	}
	storage.docs[queuedDoc.ID.Hex()] = queuedDoc

	result, err := engine.ExecuteOne(ctx, queuedDoc.ID.Hex(), ownerID)
	if err != nil {
		t.Fatalf("ExecuteOne lỗi: %v", err)
	}
	if result.ID != executedDoc.ID {
		t.Errorf("ExecuteOne phải trả doc đã xử lý (idempotency skip), got id %s", result.ID.Hex())
	}
}
